version: '3.9'
services:
  replicatoor:
    image: replicatoor
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - CONTRACT=0x2c5032c6b1ec3d13acc81758d83e0b4478e153ff
      - ETH_RPC_URL=https://base-mainnet.g.alchemy.com/v2/
      - CHAIN_ID=8453
