version: '3.9'
services:
  replicatoor:
    image: socrates1024/replicatoor
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /tmp/tapp-ramdisk:/tmp/tapp-ramdisk
    environment:
      - SECURE_FILE=/tmp/tapp-ramdisk/private.env
      - CONTRACT=0x2c5032c6b1ec3d13acc81758d83e0b4478e153ff
      - HELIOS_PARAM=opstack --network base
    networks:
      my_network:
        ipv4_address: 172.16.238.10

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
